server:
  port: 8090

spring:
  application:
    name: hospital-finance
  profiles:
    active: instanca1
  config:
    import: configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/bolnica_finance?useSSL=false&serverTimezone=UTC
    username: root
    password: NovaSifra123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

grpc:
  client:
    system-events:
      address: static://localhost:9095
      enableKeepAlive: true
      negotiationType: plaintext


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: docker