<<<<<<< HEAD:EMR/src/main/resources/application.yml
server:
  port: 8083

spring:
  application:
    name: elektronski-karton-servis

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/EMR?serverTimezone=UTC
    username: root
    password: JanaJana26*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          time_zone: UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

=======
spring:
  config:
    import: configserver:http://localhost:8888
>>>>>>> main:EMR/EMR/src/main/resources/application.yml
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
<<<<<<< HEAD:EMR/src/main/resources/application.yml
grpc:
  client:
    system-events:
      address: static://localhost:9090
      enableKeepAlive: true
      negotiationType: plaintext
=======

server:
  port: 8081
>>>>>>> main:EMR/EMR/src/main/resources/application.yml
