spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EMR
    username: root
    password: JanaJana26*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc.time_zone: UTC

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.example.elektronski_karton_servis: DEBUG
    org.springframework.web: DEBUG
    com.github.fge: DEBUG
    com.fasterxml.jackson: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
