spring:
  application:
    name: hospital-finance

  datasource:
    url: jdbc:mysql://localhost:3306/bolnica
    username: root
    password: Zbirka0801@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  cloud:
    compatibility-verifier:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
