server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/Users/DT User/Desktop/hospital-management/config-data
      label: main
  profiles:
    active: native
