server:
  port: 8085

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      routes:
        # 1. NAJSPECIFIČNIJE RUTE PRVO (po dužini patha)
        - id: client-emr-bypass
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/emr/kartoni/*/dijagnoze
          filters:
            - AddRequestHeader=X-Internal-Request, true
        - id: client-patient-emr
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/patient-emr/**

        - id: client-emr-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/emr/**

        - id: client-reports
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/reports/**
        # 2. User management rute
        - id: client-service-users
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/users/**
        # 3. Hospital Finance direktno
        - id: hospital-finance-direct
          uri: http://localhost:8090
          predicates:
            - Path=/izvjestaji/**

        # 4. EMR servis direktno
        - id: emr-service-direct
          uri: http://localhost:8082
          predicates:
            - Path=/api/emr/**
        # 5. NAJOPŠTIJE RUTE POSLEDNJE - ova hvata sve ostalo
        - id: client-service-other
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: VGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LXRvLWdlbmVyYXRlLUpXVHMhIQ==

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG