server:
  port: 8085

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false

    discovery:
      enabled: true

    gateway:
      routes:
        - id: client-service-users
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/users/**

        - id: client-service-api
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
          filters:
            - RewritePath=/api/client/(?<segment>.*), /api/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
