server:
  port: 8085

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false

    discovery:
      enabled: true

    gateway:
      routes:
        - id: client-emr-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/client/emr/**

        - id: client-service-users
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/users/**

        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**

        - id: emr-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/emr/**

        - id: client-service-api
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
          filters:
            - RewritePath=/api/client/(?<segment>.*), /api/${segment}

        # ✅ NOVA RUTA ZA FAKTURE
        - id: hospital-finance
          uri: lb://HOSPITAL-FINANCE
          predicates:
            - Path=/api/client/patients-with-invoices/**
          filters:
            - RewritePath=/api/client/patients-with-invoices/(?<segment>.*), /patients-with-invoices/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

jwt:
  secret: VGhpcy1pcy1hLXN1cGVyLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LXRvLWdlbmVyYXRlLUpXVHMhIQ==

  profiles:
    active: docker
