server:
  port: 8092

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://mysql:3306/client_service_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

grpc:
  client:
    system-events:
      address: static://system-events:9091
      enable-keep-alive: true
      negotiation-type: plaintext
