spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientdb?useSSL=false&serverTimezone=UTC
    username: root
    password: NovaSifra123!
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

application:
  name: client-service

grpc:
  client:
    system-events:
      address: discovery:///system-events
      enableKeepAlive: true
      negotiationType: plaintext



jwt:
  secret: VGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LXRvLWdlbmVyYXRlLUpXVHMhIQ==

  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka




