server:
  port: 8888

spring:
  profiles:
    active: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iosmankovi2/hospital-config
          clone-on-start: true
          default-label: main
          force-pull: true
  application:
    name: config-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
